export const myProjects = [
    {
        id: 7,
        title: "Cur8",
        description: `Cur8: The Ultimate NFT Experience \n
        Discover the most advanced platform for NFTs, designed to seamlessly manage, showcase, and enhance your digital assets across multiple blockchains—all in one secure hub. Explore curated collections of art, music, photography, and more while connecting directly with creators and collectors worldwide.`,
        techStack: "ReactJS | Redux | JavaScript | HTML | Tailwind CSS",
        thumbnail: "/Recent-Projects/cur8.webp",
        gitHubLink: "",
        live: "https://www.cur8.io/home",
        videoSrc: '',
    },
    {
        id: 1,
        title: "Tagpay",
        description: "Tagpay is an elegantly designed static website meticulously crafted to showcase the cutting-edge features and applications of innovative biometric card technology.",
        techStack: "HTML | CSS | JavaScript | jQuery",
        thumbnail: "/Recent-Projects/Tagpay.png",
        gitHubLink: "",
        live: "https://tagbiometrics.io/",
        videoSrc: '',
    },
    {
        id: 2,
        title: "Future Grail",
        description: "This online platform presents an extensive collection of rare wristwatches, pocket watches, and significant artifacts. Leveraging digital currency for seamless product transactions,  integration of blockchain technology, coupled with a profound understanding of the watch industry, spearheads a transformative era in the realm of watch collecting.",
        techStack: "NextJS | styled-components | TypeScript | Metamask | Calendly",
        thumbnail: "/Recent-Projects/FututreGrail.png",
        gitHubLink: "",
        live: "https://www.futuregrail.com/",
        videoSrc: '',
    },
    {
        id: 3,
        title: "Book Club",
        description: "A book club webpage where user can browse books, intract with other people and talk about their favorite books",
        techStack: " ReactJS | Redux | Socket io | MongoDB | JavaScript | HTML | CSS",
        thumbnail: "/book_club.png",
        gitHubLink: "https://github.com/sreerag-rajan/book-club",
        live: "https://book-club-project.vercel.app/",
        videoSrc: '',
    },
    {
        id: 4,
        title: "Webo",
        description: "A static website with some dummy contents",
        techStack: "ReactJS | SASS | Tailwind | HTML | CSS ",
        thumbnail: "/Webo.png",
        gitHubLink: "https://github.com/ThOmas-Saji/webo",
        live: "https://webo-one.vercel.app/",
        videoSrc: '',
    },
    {
        id: 5,
        title: "Weather App 2.0",
        description: "A simple webpage for checking the current and future weather status.",
        techStack: "ReactJS | contextapi | Bootstrap | HTML | CSS | TypeScript",
        thumbnail: "/WA.png",
        gitHubLink: "https://github.com/ThOmas-Saji/Weather-App-2.0",
        live: "https://weather-app-2-0-snowy.vercel.app/",
        videoSrc: '',
    },
    {
        id: 6,
        title: "Capital Movies",
        description: "Movies webpage where user can see latest and popular movies and details, if user logged in he can create a favorite movies list",
        techStack: " ReactJS | Redux-toolkit | Nodejs | Express | MongoDB | JavaScript | CSS | Material UI",
        thumbnail: "/CapitalMovies.png",
        gitHubLink: "https://github.com/ThOmas-Saji/Capital-Movies",
        live: "https://capital-movies-ten.vercel.app/discover/popular",
        videoSrc: '',
    },

]