export const myProjects = [
    {
        id: 1,
        title: "Book Club",
        description: "A book club webpage where user can browse books, intract with other people and talk about their favorite books",
        techStack: " ReactJS | Redux | Socket io | MongoDB | JavaScript | HTML | CSS",
        thumbnail: "/book_club.png",
        gitHubLink: "https://github.com/sreerag-rajan/book-club",
        live: "https://book-club-project.vercel.app/",
        videoSrc: '',
    },
    {
        id: 2,
        title: "Capital Movies",
        description: "Movies webpage where user can see latest and popular movies and details, if user logged in he can create a favorite movies list",
        techStack: " ReactJS | Redux-toolkit | Nodejs | Express | MongoDB | JavaScript | CSS | Material UI",
        thumbnail: "/CapitalMovies.png",
        gitHubLink: "https://github.com/ThOmas-Saji/Capital-Movies",
        live: "https://capital-movies-ten.vercel.app/discover/popular",
        videoSrc: '',
    },
    {
        id: 3,
        title: "Weather App 2.0",
        description: "A simple webpage for checking the current and future weather status.",
        techStack: "ReactJS | contextapi | Bootstrap | HTML | CSS | TypeScript",
        thumbnail: "/WA.png",
        gitHubLink: "https://github.com/ThOmas-Saji/Weather-App-2.0",
        live: "https://weather-app-2-0-snowy.vercel.app/",
        videoSrc: '',
    },
    {
        id: 4,
        title: "Webo",
        description: "A static website with some dummy contents",
        techStack: "ReactJS | SASS | Tailwind | HTML | CSS ",
        thumbnail: "/Webo.png",
        gitHubLink: "https://github.com/ThOmas-Saji/webo",
        live: "https://webo-one.vercel.app/",
        videoSrc: '',
    },
]